replicaCount: 2

image:
  repository: 970479985461.dkr.ecr.us-east-1.amazonaws.com/credit-card
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
