# Helm chart values
prometheus:
  service:
    type: "LoadBalancer"
    annotations:
      # service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
  additionalPodMonitors:
    - name: "crossplane"
      namespaceSelector:
        matchNames:
          - "crossplane-system"
      podMetricsEndpoints:
        - port: "metrics"
      selector: {}
  additionalServiceMonitors:
    - name: "argocd"
      namespaceSelector:
        matchNames:
          - "argocd"
      endpoints:
        - port: "http-metrics"
          path: /metrics
      selector:
        matchLabels:
          # prometheus.io/scrape: "true"
          pspcontrolplanemetrics: "argocd"
grafana:
  # adminPassword: {{ randAlphaNum 20 | b64enc }}
  service:
    type: "LoadBalancer"
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
      # service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
  resources:
    requests:
      cpu: "100m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://kube-prometheus-stack-prometheus.kube-prometheus-stack:9090/
          isDefault: false
          uid: prometheusdatasource
      deleteDatasources:
        - name: Prometheus
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "default"
          orgId: 1
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      crossplane:
        gnetId: 21169
        revision: 1
        datasource: prometheusdatasource
      argocd:
        gnetId: 14584
        revision: 1
        datasource: prometheusdatasource
      eks:
        gnetId: 14623
        revision: 1
        datasource: prometheusdatasource
      ekscontrolplane:
        gnetId: 21192
        revision: 1
        datasource: prometheusdatasource
